In [19]:
import warnings
warnings.filterwarnings('ignore')

In [20]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [21]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [22]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [23]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [24]:
# Create our features
X_df = df.drop(columns=['loan_status'])

# encoding for columns that aren't numerical 
X = pd.get_dummies(X_df, columns=["home_ownership","verification_status","issue_d",
                                  "pymnt_plan","initial_list_status","next_pymnt_d","debt_settlement_flag",
                                  "application_type","hardship_flag"], drop_first = True)

# Create our target
y = df['loan_status'].to_frame()
y.value_counts()

loan_status
low_risk       68470
high_risk        347
dtype: int64

In [25]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT,verification_status_Source Verified,verification_status_Verified,issue_d_Jan-2019,issue_d_Mar-2019,initial_list_status_w,next_pymnt_d_May-2019,application_type_Joint App
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.526309,0.106747,0.357659,0.373992,0.148001,0.451066,0.177238,0.876121,0.616839,0.139660
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.499311,0.308793,0.479314,0.483865,0.355104,0.497603,0.381873,0.329446,0.486161,0.346637
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [26]:
# Check the balance of our target values
y['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)
Counter(y_train)

Counter({'loan_status': 1})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [28]:
# DELIVERABLE 3______________DELIVERABLE 3______________DELIVERABLE 3______________DELIVERABLE 3______________DELIVERABLE 3______________
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
# Instantiate
brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fit
brfc.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [29]:
# Calculated the balanced accuracy score
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7790841584158417

In [30]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["High Risk Actual 0", "Low Risk Actual 1"], columns=["Predicted 0", "Predicted 1"])
cm_df

                    Predicted 0  Predicted 1
High Risk Actual 0           69           32
Low Risk Actual 1          2138        14966

In [31]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.68      0.88      0.06      0.77      0.59       101
   low_risk       1.00      0.88      0.68      0.93      0.77      0.61     17104

avg / total       0.99      0.87      0.68      0.93      0.77      0.61     17205

In [33]:
# List the features sorted in descending order by feature importance
sorted(zip(brfc.feature_importances_, X.columns), reverse=True)

[(0.08174729468127145, 'total_rec_prncp'),
 (0.0704288149230542, 'total_rec_int'),
 (0.06355397621943987, 'total_pymnt'),
 (0.05781429116024862, 'total_pymnt_inv'),
 (0.04746884969402229, 'last_pymnt_amnt'),
 (0.02582721646793904, 'int_rate'),
 (0.022140833882382863, 'issue_d_Jan-2019'),
 (0.019562970252637583, 'installment'),
 (0.019205431227543972, 'mths_since_recent_inq'),
 (0.01680225283509638, 'il_util'),
 (0.015642588199425694, 'mo_sin_old_rev_tl_op'),
 (0.015424455358975775, 'total_bc_limit'),
 (0.01522113810825148, 'mo_sin_old_il_acct'),
 (0.015126934082372343, 'out_prncp_inv'),
 (0.015084874864492172, 'tot_hi_cred_lim'),
 (0.014970748537634741, 'max_bal_bc'),
 (0.014884486086559848, 'total_il_high_credit_limit'),
 (0.014795068085180139, 'dti'),
 (0.014666849938887996, 'bc_open_to_buy'),
 (0.014473243906024363, 'annual_inc'),
 (0.01435348274666675, 'out_prncp'),
 (0.014327331426279179, 'mths_since_rcnt_il'),
 (0.014137663531707815, 'avg_cur_bal'),
 (0.013234029919319648, 'loan_amnt'),
 (0.01285968988008166, 'total_rev_hi_lim'),
 (0.012816275950793918, 'revol_bal'),
 (0.012264409709682504, 'num_bc_tl'),
 (0.012137973401207895, 'total_bal_il'),
 (0.01204034606007334, 'bc_util'),
 (0.011912676556379703, 'issue_d_Mar-2019'),
 (0.01182490208260541, 'num_rev_accts'),
 (0.011676102248288914, 'tot_cur_bal'),
 (0.011336562927198514, 'acc_open_past_24mths'),
 (0.011167248138160894, 'inq_last_12m'),
 (0.011036830850334625, 'mths_since_recent_bc'),
 (0.011020387251726934, 'total_bal_ex_mort'),
 (0.010210346073929694, 'all_util'),
 (0.01009484259084128, 'mo_sin_rcnt_tl'),
 (0.00973945057389155, 'mo_sin_rcnt_rev_tl_op'),
 (0.008852419385851535, 'num_il_tl'),
 (0.008638322400366999, 'pct_tl_nvr_dlq'),
 (0.008381300884877893, 'num_tl_op_past_12m'),
 (0.008360224134890274, 'total_acc'),
 (0.008311306487483721, 'num_sats'),
 (0.008267581366965303, 'num_actv_rev_tl'),
 (0.007913637232847232, 'num_rev_tl_bal_gt_0'),
 (0.007893769527329215, 'percent_bc_gt_75'),
 (0.007891580388165485, 'num_op_rev_tl'),
 (0.007367312634755418, 'open_il_24m'),
 (0.007273411240345149, 'num_actv_bc_tl'),
 (0.007125505028836717, 'open_acc'),
 (0.007037493972325654, 'total_rec_late_fee'),
 (0.006964127144319108, 'open_rv_24m'),
 (0.0069008027155080184, 'total_cu_tl'),
 (0.006774183009672064, 'num_bc_sats'),
 (0.006644874248212506, 'next_pymnt_d_May-2019'),
 (0.0065933124316302555, 'inq_fi'),
 (0.006127822876112509, 'open_act_il'),
 (0.005802748839002151, 'inq_last_6mths'),
 (0.005689066882071583, 'open_acc_6m'),
 (0.005611942719503205, 'open_il_12m'),
 (0.004557034486950842, 'mort_acc'),
 (0.00449023830327627, 'delinq_2yrs'),
 (0.00397091807649912, 'open_rv_12m'),
 (0.003960105633679818, 'num_accts_ever_120_pd'),
 (0.0038393566073338424, 'tot_coll_amt'),
 (0.0026235885780860916, 'home_ownership_MORTGAGE'),
 (0.0023976897403055254, 'verification_status_Verified'),
 (0.002240760330313251, 'pub_rec'),
 (0.0020521336634953353, 'application_type_Joint App'),
 (0.0016098645550328367, 'home_ownership_OWN'),
 (0.0011734939885666197, 'pub_rec_bankruptcies'),
 (0.0009680798978889897, 'home_ownership_RENT'),
 (0.0008532757767387901, 'num_tl_90g_dpd_24m'),
 (0.0008530690858927718, 'verification_status_Source Verified'),
 (0.0007228437951817597, 'initial_list_status_w'),
 (0.00016685213399589578, 'collections_12_mths_ex_med'),
 (6.507936507936507e-05, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'delinq_amnt'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [34]:
# Train the EasyEnsembleClassifier
from imblearn.ensemble import EasyEnsembleClassifier
# Instantiate
eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)

# Fit
eec.fit(X_train, y_train)

EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [35]:
# Calculate the balanced accuracy score
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9317770031212663

In [36]:
# Display the confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(
    cm, index=["High Risk Actual 0", "Low Risk Actual 1"], columns=["Predicted 0", "Predicted 1"])
cm_df

                    Predicted 0  Predicted 1
High Risk Actual 0           93            8
Low Risk Actual 1           979        16125

In [37]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.09      0.92      0.94      0.16      0.93      0.87       101
   low_risk       1.00      0.94      0.92      0.97      0.93      0.87     17104

avg / total       0.99      0.94      0.92      0.97      0.93      0.87     17205